# Configuration du site Jekyll
title: Auto-Ecole Pit Lane à Nyon
description: "Auto-Ecole Pit Lane"
url: "https://www.pitlane-autoecole.ch"
source: src

# Réseaux sociaux
socials:
    facebook: "https://www.facebook.com/Maximelemoniteur/"
    mail: "max@pitlane-autoecole.ch"
    instagram: "https://www.instagram.com/pitlane_autoecole"
    phone: "+41788905038"

# Chemin d'accès aux fichiers (assets)
assets:
    css: "/assets/css"
    js: "/assets/js"
